definitions:
  controller.CreateAttendancePeriodRequest:
    properties:
      end_date:
        example: "2025-01-31"
        type: string
      start_date:
        example: "2025-01-01"
        type: string
    type: object
  controller.CreateOvertimeRequest:
    properties:
      hours:
        example: 1
        type: integer
    type: object
  controller.CreatePayslipRequest:
    properties:
      period_id:
        example: 0370f6f0-5762-4bbe-a57c-b398c2c76dd2
        type: string
    type: object
  controller.CreateReimbursementRequest:
    properties:
      amount:
        example: 100000
        type: integer
      date:
        example: "2025-01-01"
        type: string
      description:
        example: Transportation
        type: string
    type: object
  controller.CreateSalaryRequest:
    properties:
      amount:
        example: 100000
        type: integer
      is_active:
        example: true
        type: boolean
      user_id:
        example: 369e9c16-2df2-4a18-ab83-d6c0065ecfce
        type: string
    type: object
  controller.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  controller.RegisterRequest:
    properties:
      full_name:
        type: string
      password:
        type: string
      user_role:
        type: string
      username:
        type: string
    type: object
  controller.RunPayrollRequest:
    properties:
      period_id:
        example: 0370f6f0-5762-4bbe-a57c-b398c2c76dd2
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/attendance_period:
    post:
      consumes:
      - application/json
      description: Only admin can create an attendance period by providing start and
        end dates
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Attendance Period Payload
        in: body
        name: attendance_period
        required: true
        schema:
          $ref: '#/definitions/controller.CreateAttendancePeriodRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create a new attendance period
      tags:
      - Attendance Period
  /admin/payroll:
    post:
      consumes:
      - application/json
      description: Admin can run payroll by providing period id
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payroll Payload
        in: body
        name: payroll
        required: true
        schema:
          $ref: '#/definitions/controller.RunPayrollRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Run payroll
      tags:
      - Payroll
  /admin/payslip-summary:
    get:
      consumes:
      - application/json
      description: Get payslip summary
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Start date
        in: query
        name: start_date
        required: true
        type: string
      - description: End date
        in: query
        name: end_date
        required: true
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of attendance periods per page
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get payslip summary
      tags:
      - Payslip
  /admin/salary:
    post:
      consumes:
      - application/json
      description: Only admin can create a salary by providing user id, amount, is
        active, ip address and created by
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Salary request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.CreateSalaryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create a new salary
      tags:
      - Salary
  /attendance:
    post:
      consumes:
      - application/json
      description: Employee can create an attendance
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create a new attendance
      tags:
      - Attendance
  /attendance_period:
    get:
      consumes:
      - application/json
      description: Get attendance period list
      parameters:
      - description: Start date
        in: query
        name: start_date
        type: string
      - description: End date
        in: query
        name: end_date
        type: string
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of attendance periods per page
        in: query
        name: page_size
        type: integer
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Get attendance period list
      tags:
      - Attendance Period
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login a user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Login a user
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register a new user
      tags:
      - Auth
  /overtime:
    post:
      consumes:
      - application/json
      description: Employee can create an overtime
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Overtime Payload
        in: body
        name: overtime
        required: true
        schema:
          $ref: '#/definitions/controller.CreateOvertimeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create a new overtime
      tags:
      - Overtime
  /payslip:
    post:
      consumes:
      - application/json
      description: Employee can generate a payslip by providing period id
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Payslip Payload
        in: body
        name: payslip
        required: true
        schema:
          $ref: '#/definitions/controller.CreatePayslipRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Generate a new payslip
      tags:
      - Payslip
  /ping:
    get:
      consumes:
      - application/json
      description: Returns a basic pong message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - System
  /reimbursement:
    post:
      consumes:
      - application/json
      description: Employee can create a reimbursement
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Reimbursement request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/controller.CreateReimbursementRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Create a new reimbursement
      tags:
      - Reimbursement
swagger: "2.0"
