info:
  contact: {}
paths:
  /ping:
    get:
      consumes:
      - application/json
      description: Returns a basic pong message
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Health check
      tags:
      - System
swagger: "2.0"
